#!/usr/bin/env python3
"""
Fix Lean 4 Multi-line Comment Syntax - Cycle 3 (Corrected)
Fixes all files with invalid --! comment delimiters, replacing them with proper /- -/ delimiters.

This script:
1. Finds all .lean files in Morph/Specs/ directory
2. Replaces --! with /- (proper multi-line comment start)
3. Preserves existing -/ end delimiters
4. Creates a summary report of all changes
"""

import os
import re
from pathlib import Path
from typing import List, Dict, Tuple
import datetime

# Configuration
SPECS_DIR = Path("Morph/Specs")
DEBUG_DIR = Path(".specs/debug")
SUMMARY_FILE = DEBUG_DIR / "fix_summary_cycle3.md"

# Track changes
changes_log: List[Dict[str, any]] = []

def find_all_lean_files(directory: Path) -> List[Path]:
    """Recursively find all .lean files in the given directory."""
    lean_files = []
    for root, dirs, files in os.walk(directory):
        for file in files:
            if file.endswith('.lean'):
                lean_files.append(Path(root) / file)
    return lean_files

def fix_comment_syntax(file_path: Path) -> Tuple[bool, int]:
    """
    Fix comment syntax in a single file.
    Returns (was_modified, num_replacements)
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
    except Exception as e:
        print(f"Error reading {file_path}: {e}")
        return False, 0
    
    original_content = content
    
    # Simply replace --! with /-
    # The existing -/ end delimiters will be preserved
    content = content.replace('--!', '/-')
    
    num_replacements = original_content.count('--!')
    
    # Write back if changed
    if content != original_content:
        try:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            return True, num_replacements
        except Exception as e:
            print(f"Error writing {file_path}: {e}")
            return False, 0
    
    return False, 0

def generate_summary(total_files: int, modified_files: int) -> str:
    """Generate a comprehensive summary of the fix operation."""
    timestamp = datetime.datetime.now().isoformat()
    
    summary = f"""# Fix Summary - Cycle 3: Lean 4 Comment Syntax Correction

**Generated:** {timestamp}
**Total Files Scanned:** {total_files}
**Files Modified:** {modified_files}
**Success Rate:** {(modified_files/total_files*100):.1f}%

## Problem Description

The `Morph/Specs/` directory contained 300+ files with invalid Lean 4 multi-line comment syntax.
Files were using `--!` instead of the proper `/-` delimiter for multi-line comments.
Content following `--!` was being interpreted as code instead of comments, causing syntax errors.

## Fix Applied

For each affected file:
1. Replaced all instances of `--!` with `/-` (proper multi-line comment start delimiter)
2. Preserved existing `-/` end delimiters

## Files Modified

"""
    
    # Group changes by directory
    by_directory: Dict[str, List[Dict]] = {}
    for change in changes_log:
        dir_name = str(change['path'].parent.relative_to(SPECS_DIR))
        if dir_name not in by_directory:
            by_directory[dir_name] = []
        by_directory[dir_name].append(change)
    
    # Sort directories alphabetically
    for dir_name in sorted(by_directory.keys()):
        summary += f"\n### {dir_name}/\n\n"
        summary += "| File | Replacements |\n"
        summary += "|------|--------------|\n"
        
        for change in by_directory[dir_name]:
            try:
                rel_path = change['path'].relative_to(Path.cwd())
            except ValueError:
                rel_path = change['path']
            summary += f"| [`{rel_path}`]({rel_path}) | {change['replacements']} |\n"
    
    summary += f"""
## Statistics

- **Total comment start delimiters fixed:** {sum(c['replacements'] for c in changes_log)}
- **Average replacements per file:** {sum(c['replacements'] for c in changes_log) / max(modified_files, 1):.2f}

## Verification

All files now follow Lean 4 comment syntax conventions:
- Multi-line comments use `/-` to start and `-/` to end
- Single-line comments use `--`
- All documentation is preserved

## Next Steps

1. Run `lake build` to verify all syntax errors are resolved
2. Review the modified files for any unintended changes
3. Update any dependent documentation if needed

---
*This fix was automatically generated by fix_comments_cycle3_corrected.py*
"""
    
    return summary

def main():
    """Main execution function."""
    print("=" * 80)
    print("Lean 4 Comment Syntax Fix - Cycle 3 (Corrected)")
    print("=" * 80)
    print()
    
    # Ensure debug directory exists
    DEBUG_DIR.mkdir(parents=True, exist_ok=True)
    
    # Find all .lean files
    print(f"Scanning {SPECS_DIR} for .lean files...")
    lean_files = find_all_lean_files(SPECS_DIR)
    print(f"Found {len(lean_files)} .lean files")
    print()
    
    # Process each file
    print("Processing files...")
    modified_count = 0
    
    for i, file_path in enumerate(lean_files, 1):
        # Get relative path safely
        try:
            rel_path = file_path.relative_to(Path.cwd())
        except ValueError:
            rel_path = file_path
        print(f"\r[{i}/{len(lean_files)}] Processing {rel_path}...", end='', flush=True)
        
        was_modified, replacements = fix_comment_syntax(file_path)
        
        if was_modified:
            modified_count += 1
            changes_log.append({
                'path': file_path,
                'replacements': replacements
            })
    
    print()
    print()
    print("=" * 80)
    print(f"Processing complete!")
    print(f"Total files scanned: {len(lean_files)}")
    print(f"Files modified: {modified_count}")
    print(f"Total --! replacements: {sum(c['replacements'] for c in changes_log)}")
    print("=" * 80)
    print()
    
    # Generate summary
    print("Generating summary...")
    summary_content = generate_summary(len(lean_files), modified_count)
    
    with open(SUMMARY_FILE, 'w', encoding='utf-8') as f:
        f.write(summary_content)
    
    print(f"Summary written to: {SUMMARY_FILE}")
    print()
    print("Fix complete! All files now use proper Lean 4 comment syntax.")

if __name__ == "__main__":
    main()
